project:
  id: 04dadc4e-792a-4f1b-92b8-28389f45c0ba
  name: DS Project Template
  description: >-
    A generic template for small data science projects
  authors:
    - name: Kvn Dtrx
      mail: kvn.dtrx+git@protonmail.ch
  license:
    type: MIT
    year: 2025
    file: LICENSE.txt
forges:
  github:
    url: https://github.com/kvn-dtrx/ds-project-template
    visibility: public
