#!/usr/bin/env sh

# ---
# description: >-
#   Reports the remaining TODO strings across the project
# ---

# ---

find_mtdt_root() (
    start="${1:-${PWD}}"
    root="$(CDPATH='' cd -- "${start}" 2> /dev/null && pwd -P)" || return 1
    while [ ! -f "${root}/.mtdt.yaml" ]; do
        parent="$(dirname "${root}")"
        if [ "${parent}" = "${root}" ]; then
            printf 'No .mtdt.yaml found above %s\n' "${start}" >&2
            return 1
        fi
        root="${parent}"
    done
    printf '%s\n' "${root}"
)

OUTPUT_NAME="todos.md"
OUTPUT_DIR="target"
# REGEX='^[[:space:]]*(# |\*\*)?TODO:'
REGEX='^[[:space:]]*(#|\"#|\*\*)[[:space:]]*TODO:'

script_path="$(realpath "${0}")"
script_name="$(basename "${script_path}")"
script_dir="$(dirname "${script_path}")"
output_path="${script_dir}/${OUTPUT_DIR}/${OUTPUT_NAME}"

if ! cd "${script_dir}"; then
    printf "%s\n" \
        "CDing to script directory failed:" \
        "  ${script_dir}" \
        >&2
    exit 1
fi

git_dir="$(find_mtdt_root 2> /dev/null)"

if ! cd "${git_dir}"; then
    printf "%s\n" \
        "CDing to .mtdt.yaml project root failed:" \
        "  ${script_dir}" \
        >&2
    exit 1
fi

tmp_path="${output_path}.tmp"

git ls-files --cached --others --exclude-standard -z |
    xargs -0 grep -Hn -E "${REGEX}" 2> /dev/null |
    sed 's@^[[:space:]]*@@' |
    sed 's@^\(.*\):\([0-9]*\):@\- [\1, line \2](../../\1#L\2): @' > "${tmp_path}"

todos="$(cat "${tmp_path}")"
no_todos="$(echo "${todos}" | sed -n '$=')"

rm "${tmp_path}" "${output_path}" 2> /dev/null

{
    printf \
        '# TODOs in this repository @ %s\n\n' \
        "$(date '+%Y-%m-%dT%H:%M')"
    # shellcheck disable=SC2016
    printf \
        'This file was automatically generated by `%s`.\n\n' \
        "${script_name}"
    printf \
        'Number of TODOs: %s\n\n' \
        "${no_todos}"
    if [ "${no_todos}" -ne 0 ]; then
        printf "%s\n" \
            "**NOTE:**" \
            "" \
            "- Paths are specified relative to the root of the repository." \
            "- VS Code cannot directly jump to line numbers of notebooks." \
            "" \
            "${todos}"
    fi
} > "${output_path}"
